language: ruby
cache: bundler

rvm:
  - 2.2.2
  - 2.0.0
  - 1.9.3

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - abronow@goodworldsolutions.org
    on_failure: change
    on_success: never
